name: Build and Publish Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build APK
      run: |
        npm run bap
        npm run ba

    - name: Upload APK to GitHub Packages
      uses: actions/upload-artifact@v4
      id: android-artifact-step
      with:
        name: xq-android
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 3
        overwrite: true